# Generated by Django 3.2.12 on 2024-07-08 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название покемона')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название покемона на английском')),
                ('title_jp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название покемона на японском')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pokemons', verbose_name='Изображение покемона')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание покемона')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(null=True, verbose_name='Широта')),
                ('lon', models.FloatField(null=True, verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(blank=True, null=True, verbose_name='Появился')),
                ('disappeared_at', models.DateTimeField(blank=True, null=True, verbose_name='Исчез')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Уровень')),
                ('health', models.IntegerField(blank=True, null=True, verbose_name='Здоровье')),
                ('strength', models.IntegerField(blank=True, null=True, verbose_name='Сила')),
                ('defense', models.IntegerField(blank=True, null=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(blank=True, null=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Стихии')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение стихии')),
                ('strong_against', models.ManyToManyField(to='pokemon_entities.PokemonElementType')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(to='pokemon_entities.PokemonElementType'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolutions', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционировал'),
        ),
    ]
